version: '3'
services:
  resources:
    image: mysql
    container_name: keps_assistant_resources
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_keps_assistant
    ports:
      - "2000:3306"

  process:
    build: 
      context: ./process_unit
      args:
        - DB_HOST=resources
    container_name: keps_assistant_process
    ports:
      - "2001:2001"
    depends_on:
      - resources
    volumes:
      - ./backup:/usr/process_unit/workdir/keps_backup

  interaction:
    build: 
      context: ./interaction_unit
      args:
        - PROCESS_HOST=127.0.0.1
        - PROCESS_PORT=2001
    container_name: keps_assistant_interaction
    ports:
      - "2002:5173"
    depends_on:
      - process