version: '3'

services:
  resources:
    image: mariadb:10.3.16
    container_name: keps_assistant_resources
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_keps_assistant
    expose:
      - "3306"
    volumes:
      - ./resources_unit:/var/lib/mysql
    networks:
      keps_network:
        ipv4_address: 172.30.0.2

  process:
    build:
      context: ./process_unit
      args:
        - DB_HOST=172.30.0.2
        - CLIENT_HOST=http://127.0.0.1:5173
    container_name: keps_assistant_process
    ports:
      - "2001:2001"
    volumes:
      - ./backup:/usr/process_unit/workdir/keps_backup
    networks:
      keps_network:
        ipv4_address: 172.30.0.3

  interaction:
    build:
      context: ./interaction_unit
    container_name: keps_assistant_interaction
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_API_KEPS_ASSISTANT_MANAGEMENT=http://127.0.0.1:2001
    networks:
      keps_network:
        ipv4_address: 172.30.0.4

networks:
  keps_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16