CREATE DATABASE IF NOT EXISTS db_keps_assistant_[client_id];
CREATE DATABASE IF NOT EXISTS db_keps_assistant_logging_[client_id];

CREATE USER 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';

GRANT ALL PRIVILEGES ON *.* TO 'kepsAssistantRootDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantDatabasePassword123@#%__';

USE db_keps_assistant_[client_id];
SOURCE /initial_database/db_keps_assistant_initial.sql;

USE db_keps_assistant_logging_[client_id];
SOURCE /initial_database/db_logging_keps_assistant_initial.sql;


GRANT INSERT ON db_keps_assistant_logging_[client_id].logger_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].aktivitas_dokumen_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].cabang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].customer_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';         
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].daftar_aset_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';      
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].daftar_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].daftar_gudang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].daftar_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';      
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].daftar_perlengkapan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                               
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].divisi_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].dokumen_klien_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].faktur_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].faktur_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].faktur_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                             
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].gaji_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';             
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].hadiah_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].hasil_stok_opname_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].hitungan_penyusutan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                               
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jabatan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jenis_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';     
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jenis_gudang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';     
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jenis_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';       
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jenis_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jenis_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                              
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].jurnal_umum_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';      
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_aset_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_gudang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_harga_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                             
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_harga_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                               
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kategori_perlengkapan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                             
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kelompok_aset_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kerugian_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';         
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].kode_akun_perkiraan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                               
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].konversi_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].lain_lain_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';        
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].lembur_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].metode_penyusutan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].neraca_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pegawai_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pelunasan_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                        
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pelunasan_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                        
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pelunasan_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pengembalian_denda_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';               
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pengembalian_denda_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';               
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pengembalian_denda_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                 
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].penggunaan_perlengkapan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pengiriman_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].penyesuaian_persediaan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].perintah_stok_opname_jurnal_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                       
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].perintah_stok_opname_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                              
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].persentase_penyusutan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                             
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pesanan_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pesanan_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pesanan_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].piutang_karyawan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__'; 
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].pph2126_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].retur_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].retur_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].retur_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                              
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_konversi_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pelunasan_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pelunasan_pembelian_denda_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pelunasan_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pelunasan_penjualan_denda_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';          
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pelunasan_penjualan_denda_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pelunasan_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pengembalian_denda_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';       
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pengembalian_denda_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';       
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pengembalian_denda_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';         
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pengiriman_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                         
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pesanan_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pesanan_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_pesanan_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_retur_pembelian_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_retur_penjualan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_retur_penjualan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                      
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_transaksi_bank_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                            
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_transaksi_kas_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                             
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].rincian_transfer_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                           
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].riwayat_aktivitas_dokumen_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                         
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].riwayat_pembayaran_aktivitas_dokumen_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';              
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].satuan_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].satuan_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';      
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].status_riwayat_aktivitas_dokumen_keterangan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';       
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].status_riwayat_aktivitas_dokumen_pegawai_pelaksana_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].status_riwayat_aktivitas_dokumen_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';                  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].status_tanggungan_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].stok_awal_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__'; 
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].stok_awal_jasa_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';   
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].supplier_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';         
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].syarat_pembayaran_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].tipe_pembayaran_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].transaksi_bank_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';   
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].transaksi_kas_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';    
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].transfer_barang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';  
GRANT INSERT, SELECT, UPDATE ON db_keps_assistant_[client_id].tunjangan_uang_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';   
GRANT SELECT ON db_keps_assistant_[client_id].user_tab TO 'kepsAssistantUserDB123@#%__'@'%' IDENTIFIED BY 'kepsAssistantPassDB123@#%__';             

FLUSH PRIVILEGES;