import { BEBAN_LAINNYA_TYPE, BEBAN_OPERASIONAL_TYPE, HARGA_POKOK_PENJUALAN_TYPE, HARTA_TYPE } from "./labaRugiConstant.js";

export const AKUN_DEBET_PLUS = [
    HARTA_TYPE, BEBAN_LAINNYA_TYPE, BEBAN_OPERASIONAL_TYPE, HARGA_POKOK_PENJUALAN_TYPE
]

export const PENDAPATAN_MINUS_KODE_AKUN = [];

export const HARGA_POKOK_PENJUALAN_MINUS_KODE_AKUN = [];

export const BEBAN_OPERASIONAL_MINUS_KODE_AKUN = [];

export const PENDAPATAN_LAIN_LAIN_MINUS_KODE_AKUN = [];

export const BEBAN_LAINNYA_MINUS_KODE_AKUN = []

export const ASSET_MINUS_KODE_AKUN = []

export const UTANG_MINUS_KODE_AKUN = []

export const MODAL_MINUS_KODE_AKUN = ["302"]